name: Development Deployment

on:
  push:
    branches:
      - development

jobs:
  echo-dev:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Development
      run: echo "Deploying to Development Environment"
