name: Production Deployment

on:
  push:
    branches:
      - production

jobs:
  echo-production:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Production
      run: echo "Deploying to Production Environment"
